version: '3.8'

services:
  bot:
    build: .
    container_name: reminder-bot
    restart: always
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - REDIS_DB=0 