version: '3.8'

services:
  bot:
    build: .
    container_name: reminder-bot
    restart: always
    depends_on:
      - redis
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0

  redis:
    image: redis:7-alpine
    container_name: reminder-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  redis-data: 